### ISSUE TITLE
Brew update raises deprecation warnings

### ISSUE THREAD

**Issue by Geekfish** [eddieantonio/imgcat#3] opened 2016-08-13 07:16 UTC
Hello!

As the title suggests, when running `brew update` this morning
I received the following 🌵  warnings 🌵  :

```
➜  ~ brew update
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/eddieantonio/homebrew-eddieantonio/imgcat.rb:4:in `<class:Imgcat>'
Please report this to the eddieantonio/eddieantonio tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/eddieantonio/homebrew-eddieantonio/imgcat.rb:4:in `<class:Imgcat>'
Please report this to the eddieantonio/eddieantonio tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/eddieantonio/homebrew-eddieantonio/imgcat.rb:4:in `<class:Imgcat>'
Please report this to the eddieantonio/eddieantonio tap!
```

**Comment by eddieantonio** [comment] 2016-08-13 14:27
Hi!

Thanks for reporting this issue! However, the latest version [_does_ use `sha256`](https://github.com/eddieantonio/homebrew-eddieantonio/blob/master/imgcat.rb#L4).  This was reported and fixed in eddieantonio/homebrew-eddieantonio#1. I'm not sure why `brew update` is still giving you this warning.

So, this issue is potentially a duplicate of eddieantonio/homebrew-eddieantonio#1 or some other issue I'm unaware of.

If you do `brew update` again, does it still give you the same warning?

**Comment by Geekfish** [comment] 2016-08-17 10:35
hey @eddieantonio, thanks for looking into this report. Running `brew update` again doesn't seem to raise the warning... so this shouldn't really be a problem I guess if things are up to date!

Probably ok to close?

**Comment by eddieantonio** [comment] 2016-08-17 13:37
Thanks for checking! Sounds good—closing.

**Closed by eddieantonio** 2016-08-17 13:37 UTC
Labels: duplicate
