### ISSUE TITLE
Image is too blurry?

### ISSUE THREAD

**Issue by dmirc** [eddieantonio/imgcat#25] opened 2019-06-08 01:59 UTC
Hi,

Basically, image is not in useful condition when i print "imgcat image.png". I've tried with both jpeg and png.

I'm using MacOS 10.14.5
followed up install instructions:
$brew tap eddieantonio/eddieantonio
$brew install imgcat

[Desktop]$ imgcat --version
imgcat 2.3.0
[Desktop]$ tput colors
256
Using MacOS Terminal 2.9.5 (421.2)

<img width="1297" alt="Screen Shot 2019-06-08 at 3 52 17 AM" src="https://user-images.githubusercontent.com/43377882/59140660-f9c94280-89a0-11e9-89a9-ea5ccca7c32c.png">

**Comment by eddieantonio** [comment] 2019-06-10 18:29
This is a feature, not a bug. 🙃

`imgcat`, in its original form is supposed to print chunky, poor-resolution images with low colour depth to your terminal, for ａｅｓｔｈｅｔｉｃ reasons.

A few terminal emulators, like [iTerm2](https://www.iterm2.com/index.html), support [_direct_ display of images](https://www.iterm2.com/documentation-images.html). So one solution to this is to install iTerm2, and use `imgcat`. `imgcat` should automatically detect it's running in iTerm2 and print the image to screen in its full resolution glory. You can still print chunky images with command line options, though!

An alternative to this is using the `-H` or `--half-height` option, which cleverly uses Unicode half-height block characters to double the vertical resolution of your screen. This might make images a little clearer, but it does not work well for diagrams, or images with text.

Consider displaying [an XKCD comic](https://xkcd.com/1475/).

With macOS Terminal, normally:

![Screen Shot 2019-06-10 at 12 17 50 PM](https://user-images.githubusercontent.com/2294397/59217145-8e3acd00-8b7a-11e9-90f3-3532c59b7327.png)

With macOS Terminal, using the `--half-height` option:

![Screen Shot 2019-06-10 at 12 21 55 PM](https://user-images.githubusercontent.com/2294397/59217169-985ccb80-8b7a-11e9-8199-2de1df6064f2.png)


With iTerm2, using its direct image output:

![Screen Shot 2019-06-10 at 12 18 48 PM](https://user-images.githubusercontent.com/2294397/59217232-b88c8a80-8b7a-11e9-8c29-3e32a24a5f79.png)

**Note**: if you switch to iTerm2, it _also_ bundles a script called `imgcat`. Follow the notes in the `brew info imgcat` in order to install _this_ version of `imgcat` correctly.

I'm marking this as `wontfix`, but if you have any questions, feel free to reply! 😄

**Closed by eddieantonio** 2019-06-10 18:29 UTC
